### ISSUE TITLE
Can't install on EdgeRouter X

### ISSUE THREAD

**Issue by ian5142** [tylerrichey/darkstatscore#4]
I tried to install this on my EdgeRouter X. dpkg exits with exit status 2. I do have darkstat installed. Another try ended with not enough space.

How do I install this on the EdgeRouter X? I have PuTTY and linux command exerience, but I can't seem to get it to install.

**Comment by tylerrichey** [comment]
Resolved via email. Changed github settings to make sure I get an email for new issues.
